### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by M-Saeidi** [steven-cheng-com/grammar_correction_with_bert#2]
Hi, thanks for your amazing work. I want to deploy your model for a project. However, I have difficulties in understanding the model file with ".th" extension. Typically, we pickle the model and use the pickled model for deployment using Flask. However,  I do not know how to approach ".th" model file. I will appreciate it if you can provide me any clarification or hint in this regard. Thank you!

**Comment by stephen-cheng** [comment]
U can download from links in Pretrained models section

**Comment by steven-cheng-com** [comment]
> Hi, thanks for your amazing work. I want to deploy your model for a project. However, I have difficulties in understanding the model file with ".th" extension. Typically, we pickle the model and use the pickled model for deployment using Flask. However, I do not know how to approach ".th" model file. I will appreciate it if you can provide me any clarification or hint in this regard. Thank you!
